### PR TITLE
use conan_target_link_libraries()

### PR DESCRIPTION
**Pull request by ClausKlein**
prevent conan warnings
autopep8 py files too

### CODE REVIEW

**Comment by memsharded** [comment]
Good, I have added a ``conan test`` line to the flow too, and a couple of comments. I agree it is very nice to have the example of the full parameterized flow with clean "tmp" folder.

Thanks very much, you are doing a great job with this revisions and updating and improving these docs and examples.

**Comment by ClausKlein** [comment]
Thanks, I forget the test, I noticed it later.

Today I have tested under msys  on a Windows PC and the test_package die not link. The link path to the lib was not set?
The old version with target_link_libraries(example ${CONAN_LIBS}) works!

Do you have test und msys (from msys2.org) too?
On my macbook (OSX) I had no problems.


> Am 28.03.2018 um 10:01 schrieb James <notifications@github.com>:
> 
> Good, I have added a conan test line to the flow too, and a couple of comments.

**Comment by memsharded** [comment]
Hi @ClausKlein 

No, I haven't tested under msys2, though I know some people are using conan with msys2. It might require some tweaks to the recipes or to the environment. Are you still seing this issue or did you manage to solve it? Maybe it deserves an issue in the main github repo. Thanks!

**Comment by ClausKlein** [comment]
The CMAKE_SYSNAME is wrong set, so find_library() does not work under conan and msys2

**Comment by memsharded** [comment]
CMAKE_SYSNAME? You meant CMAKE_SYSTEM_NAME?
Might be an issue of the environment detection, which profile are you using? I still think that this could be better followed in a dedicated issue in the conan repo, is it an issue that affects any project under conan with msys2? Thanks!

**Comment by ClausKlein** [comment]
see https://github.com/bincrafters/community/issues/205

**Pull request merged**
